name: Test 🧪

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Prepare Clojure
        uses: DeLaGuardo/setup-clojure@10.1
        with:
          cli: 1.11.1.1208
      - name: Run Tests
        run: clojure -X:test-runner